### PR TITLE
Add support for ft=qf

### PR DESCRIPTION
**Pull request by perelo**
Here we are...

I tried `\%#=1` for old regex engine and it actually does help for thousands of lines.

For the comment, how about something like "First error in the next/current file" inspired from `:h :cnf` ?

### CODE REVIEW

**Comment by arp242** [comment]
The tests are failing (not reported here because of error in .travis.yml, hopefully fixed in master now): https://travis-ci.org/arp242/jumpy.vim/builds/572074300#L235

The problem is that the `filetype` isn't being set, since the tests rely on it being set correctly from the ftdetect.

Can set it from the extension with something like:
```
diff --git i/autoload/jumpy_test.vim w/autoload/jumpy_test.vim
index f1bfe8b..d4daf2e 100644
--- i/autoload/jumpy_test.vim
+++ w/autoload/jumpy_test.vim
@@ -26,6 +26,9 @@ fun! Test_jumpy() abort
                        return Errorf('unable to read "%s"', l:file)
                endif
                exe 'e ' . l:file
+               if &filetype is# ''
+                       let &filetype = fnamemodify(l:file, ':e')
+               endif

                " Should jump to last line if there are no more matches (also tests if
                " there are no matches after wantlines).
```

> For the comment, how about something like "First error in the next/current file" inspired from :h :cnf ?

Maybe just "Next/prev filename"? That seems fairly clear.

**Comment by perelo** [comment]
yes, I was on the same track, but my `test.qf` wasn't good ! It needs to not start with an empty line and first jump to `2`. Also it should end with only 1 newline.

Also, couldn't we set all extensions of testfiles to the exact filetype, e.g similar to `python.vim`, `test.python`, then set `ft` to the extension of each testfile ? It seems like `Makefile`, `.py`, `.rb` and `.js` would need to change. I don't know why but with `if &ft is# ''`, python and ruby tests failed me :/

**Comment by arp242** [comment]
> Also, couldn't we set all extensions of testfiles to the exact filetype, e.g similar to python.vim, test.python, then set ft to the extension of each testfile

What would the advantage of that be? Using the ftdetect should work for the vast majority of cases, with stuff like the quickfix window being the exception.

**Comment by perelo** [comment]
You're right, I'm picky...
Thanks for the merge :)

**Pull request merged**
